/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness (database reachable) */
    get: operations['getReady']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sign up and start a session */
    post: operations['createUser']
    delete?: never
    options?: never
    head?: never
    /** Update the signed-in user's profile */
    patch: operations['updateUser']
    trace?: never
  }
  '/api/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the current session's user */
    get: operations['getSession']
    put?: never
    /** Log in */
    post: operations['createSession']
    /** Log out */
    delete: operations['deleteSession']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/topic': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the topic taxonomy */
    get: operations['listTopics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/thread': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the user's threads, most recently updated first */
    get: operations['listThreads']
    put?: never
    /**
     * Create a thread
     * @description `topicId` defaults to `other`. An unknown topic is `validation_failed`.
     */
    post: operations['createThread']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/thread/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    /** Get a thread with its messages, guides and quizzes */
    get: operations['getThread']
    put?: never
    post?: never
    /** Delete a thread */
    delete: operations['deleteThread']
    options?: never
    head?: never
    /** Rename or re-topic a thread */
    patch: operations['updateThread']
    trace?: never
  }
  '/api/thread/{id}/message': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Ask a question and stream the answer
     * @description Streams Server-Sent Events. Events arrive in this order:
     *
     *     1. `message.start` - data is `StreamMessageStart`
     *     2. `delta` (zero or more) - data is `StreamDelta`
     *     3. exactly one of `message.complete` (data is `StreamMessageComplete`) or `error`
     *        (data is `ErrorResponse`)
     *
     *     A `: ping` comment line is sent as a heartbeat every 15 seconds. Failures before the
     *     stream starts use the plain error statuses below.
     */
    post: operations['askQuestion']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/thread/{id}/guide': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Generate a step-by-step guide from a thread */
    post: operations['createGuide']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/guide/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    /** Get a guide */
    get: operations['getGuide']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/guide/{id}/step/{stepId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
        stepId: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Mark a step done or reveal its hint */
    patch: operations['updateStep']
    trace?: never
  }
  '/api/quiz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Generate a quiz from a thread or a topic */
    post: operations['createQuiz']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quiz/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    /** Get a quiz (never includes answers or explanations) */
    get: operations['getQuiz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quiz/{id}/attempt': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit and grade an attempt */
    post: operations['submitAttempt']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quiz/{id}/attempt/{attemptId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
        attemptId: string
      }
      cookie?: never
    }
    /** Get a graded attempt */
    get: operations['getAttempt']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get learning progress */
    get: operations['getProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string
        message: string
        details?: Record<string, never>
      }
      requestId: string
    }
    User: {
      id: string
      /** Format: email */
      email: string
      displayName: string
      timeZone: string
      /** Format: date-time */
      createdAt: string
    }
    SignupRequest: {
      /** Format: email */
      email: string
      password: string
      displayName: string
      /** @description IANA time zone name */
      timeZone: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    UpdateUserRequest: {
      displayName?: string
      timeZone?: string
    }
    UserResponse: {
      user: components['schemas']['User']
    }
    Topic: {
      id: string
      name: string
    }
    TopicListResponse: {
      topics: components['schemas']['Topic'][]
    }
    Thread: {
      id: string
      topicId: string
      title: string
      messageCount: number
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    ThreadListResponse: {
      threads: components['schemas']['Thread'][]
      nextCursor: string | null
    }
    CreateThreadRequest: {
      topicId?: string
      title?: string
    }
    UpdateThreadRequest: {
      title?: string
      topicId?: string
    }
    ThreadResponse: {
      thread: components['schemas']['Thread']
    }
    /** @enum {string} */
    MessageRole: 'user' | 'assistant'
    /** @enum {string} */
    MessageStatus: 'complete' | 'incomplete' | 'failed'
    /** @enum {string} */
    StopReason: 'end_turn' | 'max_tokens' | 'stop_sequence' | 'refusal' | 'aborted' | 'error'
    Message: {
      id: string
      threadId: string
      role: components['schemas']['MessageRole']
      content: string
      status: components['schemas']['MessageStatus']
      stopReason: components['schemas']['StopReason'] | null
      /** Format: date-time */
      createdAt: string
    }
    /** @enum {string} */
    Difficulty: 'easy' | 'medium' | 'hard'
    GuideSummary: {
      id: string
      title: string
      stepCount: number
      doneCount: number
      /** Format: date-time */
      createdAt: string
    }
    QuizSummary: {
      id: string
      difficulty: components['schemas']['Difficulty']
      itemCount: number
      bestScore: number | null
      /** Format: date-time */
      createdAt: string
    }
    ThreadDetailResponse: {
      thread: components['schemas']['Thread']
      /** @description Oldest first */
      messages: components['schemas']['Message'][]
      /** @description Newest first */
      guides: components['schemas']['GuideSummary'][]
      /** @description Newest first */
      quizzes: components['schemas']['QuizSummary'][]
    }
    AskRequest: {
      content: string
    }
    /** @description Data of the `message.start` SSE event */
    StreamMessageStart: {
      threadId: string
      userMessageId: string
      assistantMessageId: string
    }
    /** @description Data of the `delta` SSE event */
    StreamDelta: {
      text: string
    }
    TokenUsage: {
      inputTokens: number
      outputTokens: number
      cacheReadTokens: number
    }
    /** @description Data of the `message.complete` SSE event. The `error` event's data is an `ErrorResponse`. */
    StreamMessageComplete: {
      messageId: string
      /** @enum {string} */
      status: 'complete' | 'incomplete'
      stopReason: components['schemas']['StopReason']
      usage: components['schemas']['TokenUsage']
    }
    Step: {
      id: string
      position: number
      title: string
      body: string
      code: string | null
      codeLanguage: string | null
      hint: string
      /** Format: date-time */
      hintRevealedAt: string | null
      /** Format: date-time */
      doneAt: string | null
    }
    Guide: {
      id: string
      threadId: string
      topicId: string
      title: string
      /** Format: date-time */
      createdAt: string
      steps: components['schemas']['Step'][]
    }
    GuideResponse: {
      guide: components['schemas']['Guide']
    }
    UpdateStepRequest: {
      done?: boolean
      /** @constant */
      hintRevealed?: true
    }
    StepResponse: {
      step: components['schemas']['Step']
    }
    /** @description Either from a thread (`threadId`, optional `difficulty`) or from a topic (`topicId` and `difficulty`). */
    CreateQuizRequest:
      | {
          threadId: string
          difficulty?: components['schemas']['Difficulty']
        }
      | {
          topicId: string
          difficulty: components['schemas']['Difficulty']
        }
    /** @description Taker view; never includes the answer key. */
    QuizItem: {
      id: string
      position: number
      prompt: string
      choices: string[]
    }
    AttemptSummary: {
      id: string
      score: number
      /** @constant */
      total: 5
      /** Format: date-time */
      submittedAt: string
    }
    Quiz: {
      id: string
      threadId: string | null
      topicId: string
      difficulty: components['schemas']['Difficulty']
      /** Format: date-time */
      createdAt: string
      items: components['schemas']['QuizItem'][]
      /** @description Newest first */
      attempts: components['schemas']['AttemptSummary'][]
    }
    QuizResponse: {
      quiz: components['schemas']['Quiz']
    }
    SubmitAttemptRequest: {
      answers: {
        itemId: string
        choiceIndex: number
      }[]
    }
    GradedItem: {
      itemId: string
      position: number
      prompt: string
      choices: string[]
      choiceIndex: number
      answerIndex: number
      correct: boolean
      explanation: string
    }
    Attempt: {
      id: string
      quizId: string
      score: number
      /** @constant */
      total: 5
      /** Format: date-time */
      submittedAt: string
      items: components['schemas']['GradedItem'][]
    }
    AttemptResponse: {
      attempt: components['schemas']['Attempt']
    }
    TopicProgress: {
      topicId: string
      topicName: string
      questions: number
      guidesCompleted: number
      stepsDone: number
      attempts: number
      /** @description Highest single attempt, 0-100 */
      bestScorePercent: number | null
      /** @description Mean of each quiz's best attempt, 0-100 (the topic score) */
      averageScorePercent: number | null
      /** Format: date-time */
      lastActivityAt: string | null
    }
    Streak: {
      current: number
      longest: number
      activeToday: boolean
    }
    ProgressTotals: {
      questions: number
      guidesCompleted: number
      stepsDone: number
      attempts: number
    }
    /** @enum {string} */
    ActivityKind: 'question' | 'step' | 'attempt'
    Activity: {
      kind: components['schemas']['ActivityKind']
      /** Format: date-time */
      at: string
      topicId: string
      title: string
      threadId: string | null
      guideId: string | null
      quizId: string | null
    }
    ProgressResponse: {
      totals: components['schemas']['ProgressTotals']
      streak: components['schemas']['Streak']
      /** @description Every topic, in taxonomy order */
      topics: components['schemas']['TopicProgress'][]
      /** @description Newest first */
      recent: components['schemas']['Activity'][]
    }
  }
  responses: {
    /** @description Missing or invalid session (`unauthenticated`) */
    Unauthenticated: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Resource does not exist or belongs to another user (`not_found`) */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Invalid input (`validation_failed`, `malformed_json`) */
    ValidationFailed: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Request body exceeds the size limit (`payload_too_large`) */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Unexpected server error (`internal_error`) */
    InternalError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Foreign Origin on a state-changing request (`forbidden_origin`) */
    ForbiddenOrigin: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
  }
  parameters: {
    /** @description Opaque resource id */
    Id: string
  }
  requestBodies: never
  headers: {
    /** @description Session cookie `sid` (HttpOnly). Cleared with an expired cookie on logout. */
    SetCookie: string
  }
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The process is up */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            status: 'ok'
          }
        }
      }
      500: components['responses']['InternalError']
    }
  }
  getReady: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The database is reachable */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            status: 'ready'
          }
        }
      }
      500: components['responses']['InternalError']
      /** @description The database is not reachable (`db_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest']
      }
    }
    responses: {
      /** @description Account created and signed in */
      201: {
        headers: {
          'Set-Cookie': components['headers']['SetCookie']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      /** @description Email already registered (`email_taken`) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      413: components['responses']['PayloadTooLarge']
      500: components['responses']['InternalError']
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description The updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      /** @description The time zone changed less than 24 hours ago (`time_zone_recently_changed`); `error.details.nextChangeAt` is an RFC 3339 `date-time` string */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      413: components['responses']['PayloadTooLarge']
      500: components['responses']['InternalError']
    }
  }
  getSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The signed-in user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      500: components['responses']['InternalError']
    }
  }
  createSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          'Set-Cookie': components['headers']['SetCookie']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      /** @description Wrong email or password (`invalid_credentials`) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      403: components['responses']['ForbiddenOrigin']
      413: components['responses']['PayloadTooLarge']
      /** @description Too many login attempts (`rate_limited`) */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      500: components['responses']['InternalError']
    }
  }
  deleteSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Signed out; the session cookie is cleared */
      204: {
        headers: {
          'Set-Cookie': components['headers']['SetCookie']
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      500: components['responses']['InternalError']
    }
  }
  listTopics: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description All topics, in taxonomy order */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TopicListResponse']
        }
      }
      500: components['responses']['InternalError']
    }
  }
  listThreads: {
    parameters: {
      query?: {
        /** @description Opaque cursor from a previous `nextCursor` */
        cursor?: string
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A page of threads */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThreadListResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      500: components['responses']['InternalError']
    }
  }
  createThread: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateThreadRequest']
      }
    }
    responses: {
      /** @description The new thread */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThreadResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      413: components['responses']['PayloadTooLarge']
      500: components['responses']['InternalError']
    }
  }
  getThread: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The thread detail */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThreadDetailResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  deleteThread: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  updateThread: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateThreadRequest']
      }
    }
    responses: {
      /** @description The updated thread */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThreadResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      413: components['responses']['PayloadTooLarge']
      500: components['responses']['InternalError']
    }
  }
  askQuestion: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AskRequest']
      }
    }
    responses: {
      /** @description The event stream */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': string
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      /** @description Another generation is running, or the thread is full (`generation_in_progress`, `thread_full`) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      413: components['responses']['PayloadTooLarge']
      /** @description AI usage budget exhausted (`ai_budget_exceeded`) */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      500: components['responses']['InternalError']
      /** @description AI is unavailable (`ai_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createGuide: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The generated guide */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GuideResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      /** @description Another generation is running, or the thread has no answer yet (`generation_in_progress`, `thread_empty`) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The model refused (`ai_refused`) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description AI usage budget exhausted (`ai_budget_exceeded`) */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      500: components['responses']['InternalError']
      /** @description The AI output was invalid or the provider failed (`ai_invalid_output`, `ai_provider_error`) */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description AI is unavailable (`ai_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getGuide: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The guide */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GuideResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  updateStep: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
        stepId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateStepRequest']
      }
    }
    responses: {
      /** @description The updated step */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StepResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      413: components['responses']['PayloadTooLarge']
      500: components['responses']['InternalError']
    }
  }
  createQuiz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateQuizRequest']
      }
    }
    responses: {
      /** @description The generated quiz (no answer key) */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QuizResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      /** @description Another generation is running, or the thread has no answer yet (`generation_in_progress`, `thread_empty`) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      413: components['responses']['PayloadTooLarge']
      /** @description The model refused (`ai_refused`) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description AI usage budget exhausted (`ai_budget_exceeded`) */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      500: components['responses']['InternalError']
      /** @description The AI output was invalid or the provider failed (`ai_invalid_output`, `ai_provider_error`) */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description AI is unavailable (`ai_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getQuiz: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The quiz */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QuizResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  submitAttempt: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitAttemptRequest']
      }
    }
    responses: {
      /** @description The graded attempt */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AttemptResponse']
        }
      }
      400: components['responses']['ValidationFailed']
      401: components['responses']['Unauthenticated']
      403: components['responses']['ForbiddenOrigin']
      404: components['responses']['NotFound']
      413: components['responses']['PayloadTooLarge']
      /** @description Not every item was answered (`attempt_incomplete`) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      500: components['responses']['InternalError']
    }
  }
  getAttempt: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Opaque resource id */
        id: components['parameters']['Id']
        attemptId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The graded attempt */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AttemptResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProgress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Totals, streak, per-topic progress and recent activity */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProgressResponse']
        }
      }
      401: components['responses']['Unauthenticated']
      500: components['responses']['InternalError']
    }
  }
}
